#pragma once

public enum class CRecipeType
{
	Process = 0,
	Clean,
	Chuck,
	Dechuck,
};

public enum class CMOD_ID{
	MOD_ID_FOUP_A = 0,
	MOD_ID_FOUP_B = 1,
	MOD_ID_FOUP_C = 2,
	MOD_ID_FOUP_D = 3,
	MOD_ID_INT_BUFFER_STATION = 4,
	MOD_ID_EXT_BUFFER_STATION = 5,
	MOD_ID_EFEM_CLUSTER = 6,
	MOD_ID_ALIGNER = 7,
	MOD_ID_LOADLOCK_A = 8,
	MOD_ID_LOADLOCK_B = 9,
	MOD_ID_LOADLOCK_AE = 10,
	MOD_ID_LOADLOCK_BE = 11,
	MOD_ID_TRANSFER_CLUSTER = 12,
	MOD_ID_RESERVE_13 = 13,
	MOD_ID_PROCESS_MODULE_A1 = 14,
	MOD_ID_PROCESS_MODULE_A2 = 15,
	MOD_ID_PROCESS_MODULE_B1 = 16,
	MOD_ID_PROCESS_MODULE_B2 = 17,
	MOD_ID_PROCESS_MODULE_C1 = 18,
	MOD_ID_PROCESS_MODULE_C2 = 19,
	MOD_ID_EXTENSION_MODULE = 20,
	MOD_ID_RESERVE_21 = 21,
	MOD_ID_PROCESS_MODULE_D1 = 22,
	MOD_ID_PROCESS_MODULE_D2 = 23,
	MOD_ID_PROCESS_MODULE_E1 = 24,
	MOD_ID_PROCESS_MODULE_E2 = 25,
	MOD_ID_PROCESS_MODULE_F1 = 26,
	MOD_ID_PROCESS_MODULE_F2 = 27,
	MOD_ID_RESERVE_28 = 28,
	MOD_ID_RESERVE_29 = 29,
	MOD_ID_RESERVE_30 = 30,
	MOD_ID_SYSTEM = 31,
	MOD_ID_UTILITY_MODULE = 32,
	MOD_ID_WAFER_MANAGER = 33,
	MOD_ID_WAFER_HISTORY = 34,
	MOD_ID_FDC_MODULE = 35,
	MOD_ID_EQUIPMENT_CONSTANT = 36,
	MOD_ID_ATTRIBUTE_MODULE = 37,
	MOD_ID_ROUTER_MODULE = 38,
	MOD_ID_FSM_MODULE = 39,
	MOD_ID_UPS_MODULE = 40,
	MOD_ID_ETHERNET_DRIVER = 41,
	MOD_ID_RS232_DRIVER = 42,
	MOD_ID_EVENT_LOGGER = 43,
	MOD_ID_GUI_COMMAND = 44,
	MOD_ID_GUI_MODULE = 45,
	MOD_ID_MLR_HISTORY = 46,
	MOD_ID_ALL,
};

public enum class CStepType
{
	Time,
	Stable,
	OverEtch,
	Dechuck,
	Endpoint,
	RVoltage,
	EndpointBoth,
	EndpointIndividual,
};

public enum class CRampMode
{
	Linear = 0,
	Curvilinear = 1,
};

public enum class CGasZone
{
	Unknown = -1,
	Center = 0,
	Middle = 1,
	Edge = 2,
	XEdge = 3,
	Side = 4,
};

